//Game Rules Tweaks
exports.DEFAULT_MAX_TIME_MIL = 60000;

exports.GUESSER_CORRECTGUESS_BASESCORE = 500;
exports.GUESSER_MAX_BONUS_SCORE = 5500;
exports.GUESSER_BONUS_SCORE_DECAY_PER_MIL = .1;

exports.ARTIST_CORRECTGUESS_BASESCORE = 500;
exports.ARTIST_MAX_BONUS_SCORE = 5500;
exports.ARTIST_BONUS_SCORE_DECAY_PER_MIL = .1;



